const API_ERRORS = {
	USER_NOT_STUDENT_OF_CLASS: "USER_IS_NOT_STUDENT_OF_CLASS",
	COURSE_CONTENT: {
		DRAG_AND_DROP_IS_NOT_ALLOWED: "DRAG_AND_DROP_IS_NOT_ALLOWED",
	},

	// * ERRORS THAT NEED DEFAULT HANLDING
	UNAUTHORIZED: "UNAUTHORIZED",
	JWT_EXPIRED: "JWT_EXPIRES",
};

export default API_ERRORS;
